### ISSUE TITLE
The example won't compile.

### ISSUE THREAD

**Issue by mpzross** [jackmax/AccuWeatherLibrary#2]
Arduino: 1.8.7 (Windows 7), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 512000"

E:\Documents\Arduino\libraries\AccuWeatherLibrary\AccuWeatherLibrary.cpp: In member function 'int Accuweather::getCurrent(AccuweatherCurrentData*)':

E:\Documents\Arduino\libraries\AccuWeatherLibrary\AccuWeatherLibrary.cpp:586:20: error: 'class JsonStreamingParser' has no member named 'reset'

             parser.reset();

                    ^

**Comment by jackmax** [comment]
Which version of Json Streaming Parser library are you using? This library works with version 1.0.5 (the latest version).

**Comment by mpzross** [comment]
Thank you. I don't know which version it is but will check when I get home
from work.

**Comment by mpzross** [comment]
That made the difference, thank you.
